### ISSUE TITLE
发布文章失败

### ISSUE THREAD

**Issue by aafnnp** [crawlab-team/artipub#133]
仅 掘金 发布成功

**头条（已登录状态）的cookie获取不到**

``` shell
app_1    | [2021-01-14T04:50:14.004] [INFO] default - Publish task started
app_1    | [Function: JuejinSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 27.215 ms - 9712
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2021-01-14T04:50:17.515] [INFO] default - navigating to https://juejin.cn/editor/drafts/new
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 26.503 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 31.026 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 34.436 ms - -
app_1    | [2021-01-14T04:50:34.545] [INFO] default - input editor title
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 34.217 ms - -
app_1    | [2021-01-14T04:50:37.596] [INFO] default - input editor  content
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 29.611 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 22.918 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 24.109 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 22.617 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 26.223 ms - -
app_1    | 前端
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 28.692 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 22.798 ms - -
app_1    | [2021-01-14T04:51:13.745] [INFO] default - publishing article
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 28.588 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 32.842 ms - -
app_1    | [2021-01-14T04:51:23.855] [INFO] default - Publish task ended
app_1    | [2021-01-14T04:51:24.005] [INFO] default - Publish task started
app_1    | [Function: SegmentfaultSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2021-01-14T04:51:24.405] [INFO] default - navigating to https://segmentfault.com/write?freshman=1
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 31.943 ms - 9761
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 29.644 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 29.977 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 36.467 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 27.342 ms - -
app_1    | [2021-01-14T04:51:45.110] [INFO] default - input editor title
app_1    | Error: Evaluation failed: TypeError: Cannot read property 'focus' of null
app_1    |     at inputTitle (__puppeteer_evaluation_script__:3:8)
app_1    |     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1    |   -- ASYNC --
app_1    |     at ExecutionContext.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at DOMWorld.evaluate (/app/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.evaluate (/app/node_modules/puppeteer-core/lib/Page.js:833:43)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at SegmentfaultSpider.inputEditor (/app/spiders/base.js:278:21)
app_1    |     at SegmentfaultSpider.run (/app/spiders/base.js:345:16)
app_1    |     at <anonymous>
app_1    | [2021-01-14T04:51:45.146] [INFO] default - Publish task ended
app_1    | [2021-01-14T04:51:46.006] [INFO] default - Publish task started
app_1    | [Function: CsdnSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2021-01-14T04:51:46.494] [INFO] default - navigating to https://editor.csdn.net/md/
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 34.246 ms - 9896
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 22.355 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 25.948 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 30.919 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 27.703 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 20.852 ms - -
app_1    | [2021-01-14T04:52:15.231] [INFO] default - input editor title
app_1    | [2021-01-14T04:52:18.258] [INFO] default - input editor  content
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 25.634 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 23.913 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 25.328 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 35.751 ms - -
app_1    | Error: Evaluation failed: TypeError: Cannot set property 'value' of null
app_1    |     at __puppeteer_evaluation_script__:3:21
app_1    |     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1    |   -- ASYNC --
app_1    |     at ExecutionContext.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at DOMWorld.evaluate (/app/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.evaluate (/app/node_modules/puppeteer-core/lib/Page.js:833:43)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at CsdnSpider.afterInputEditor (/app/spiders/csdn.js:54:21)
app_1    |     at <anonymous>
app_1    | [2021-01-14T04:52:39.425] [INFO] default - Publish task ended
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 25.736 ms - 10019
app_1    | [2021-01-14T04:52:40.007] [INFO] default - Publish task started
app_1    | [Function: JianshuSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2021-01-14T04:52:40.352] [INFO] default - navigating to https://www.jianshu.com/writer
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 28.204 ms - 10018
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 32.478 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 33.114 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 26.791 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 33.861 ms - -
app_1    | TypeError: Cannot read property 'type' of null
app_1    |     at JianshuSpider.inputEditor (/app/spiders/jianshu.js:26:21)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1    | [2021-01-14T04:53:09.145] [INFO] default - Publish task ended
app_1    | [2021-01-14T04:53:10.005] [INFO] default - Publish task started
app_1    | [Function: ZhihuSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 43.951 ms - 10069
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2021-01-14T04:53:10.434] [INFO] default - navigating to https://zhuanlan.zhihu.com/write
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 35.498 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 26.821 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 28.874 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 31.608 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 26.191 ms - -
app_1    | [2021-01-14T04:53:37.948] [INFO] default - input editor title
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 20.978 ms - -
app_1    | [2021-01-14T04:53:40.941] [INFO] default - input editor  content
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 26.002 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 22.184 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 23.715 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 24.477 ms - -
app_1    | Error: Evaluation failed: TypeError: Cannot read property 'click' of null
app_1    |     at __puppeteer_evaluation_script__:3:10
app_1    |     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1    |   -- ASYNC --
app_1    |     at ExecutionContext.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at DOMWorld.evaluate (/app/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.evaluate (/app/node_modules/puppeteer-core/lib/Page.js:833:43)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at ZhihuSpider.afterInputEditor (/app/spiders/zhihu.js:66:21)
app_1    |     at <anonymous>
app_1    | [2021-01-14T04:54:02.101] [INFO] default - Publish task ended
app_1    | [2021-01-14T04:54:03.006] [INFO] default - Publish task started
app_1    | [Function: OschinaSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 23.157 ms - 10192
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 21.356 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 22.679 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 22.861 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 23.120 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 25.881 ms - -
app_1    | { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
app_1    |     at Promise.then (/app/node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.goto (/app/node_modules/puppeteer-core/lib/Page.js:674:49)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at OschinaSpider.goToEditor (/app/spiders/oschina.js:6:21)
app_1    |     at OschinaSpider.run (/app/spiders/base.js:342:16)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7) name: 'TimeoutError' }
app_1    | [2021-01-14T04:54:33.333] [INFO] default - Publish task ended
app_1    | [2021-01-14T04:54:34.007] [INFO] default - Publish task started
app_1    | [Function: ToutiaoSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2021-01-14T04:54:34.484] [INFO] default - navigating to https://mp.toutiao.com/profile_v3/graphic/publish
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 26.034 ms - 10256
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 31.116 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 29.284 ms - -
app_1    | [2021-01-14T04:54:48.106] [INFO] default - input editor title
app_1    | Error: Evaluation failed: TypeError: Cannot read property 'focus' of null
app_1    |     at inputTitle (__puppeteer_evaluation_script__:3:8)
app_1    |     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1    |   -- ASYNC --
app_1    |     at ExecutionContext.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at DOMWorld.evaluate (/app/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.evaluate (/app/node_modules/puppeteer-core/lib/Page.js:833:43)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at ToutiaoSpider.inputEditor (/app/spiders/base.js:278:21)
app_1    |     at ToutiaoSpider.run (/app/spiders/base.js:345:16)
app_1    |     at <anonymous>
app_1    | [2021-01-14T04:54:48.705] [INFO] default - Publish task ended
app_1    | [2021-01-14T04:54:49.005] [INFO] default - Publish task started
app_1    | [Function: CnblogsSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2021-01-14T04:54:49.356] [INFO] default - navigating to https://i.cnblogs.com/articles/edit
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 23.527 ms - 10391
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 27.077 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 22.769 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 33.956 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 38.994 ms - -
app_1    | [2021-01-14T04:55:14.262] [INFO] default - input editor title
app_1    | Error: Evaluation failed: TypeError: Cannot read property 'focus' of null
app_1    |     at inputTitle (__puppeteer_evaluation_script__:3:8)
app_1    |     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1    |   -- ASYNC --
app_1    |     at ExecutionContext.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at DOMWorld.evaluate (/app/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.evaluate (/app/node_modules/puppeteer-core/lib/Page.js:833:43)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at CnblogsSpider.inputEditor (/app/spiders/base.js:278:21)
app_1    |     at CnblogsSpider.run (/app/spiders/base.js:345:16)
app_1    |     at <anonymous>
app_1    | [2021-01-14T04:55:14.299] [INFO] default - Publish task ended
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 22.982 ms - 10527
app_1    | [2021-01-14T04:55:15.004] [INFO] default - Publish task started
app_1    | [Function: V2exSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2021-01-14T04:55:15.328] [INFO] default - navigating to https://v2ex.com/new
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 23.259 ms - 10526
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 23.019 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 26.906 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 25.079 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 24.238 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 23.265 ms - -
app_1    | { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
app_1    |     at Promise.then (/app/node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.goto (/app/node_modules/puppeteer-core/lib/Page.js:674:49)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at V2exSpider.goToEditor (/app/spiders/base.js:214:21)
app_1    |     at V2exSpider.run (/app/spiders/base.js:342:16)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7) name: 'TimeoutError' }
app_1    | [2021-01-14T04:55:45.317] [INFO] default - Publish task ended
app_1    | [2021-01-14T04:55:46.005] [INFO] default - Publish task started
app_1    | [Function: WechatSpider]
app_1    | [2021-01-14T04:55:46.017] [INFO] default - fetching access token
app_1    | [40164] invalid ip 120.237.91.166 ipv6 ::ffff:120.237.91.166, not in whitelist rid: 5fffced2-53af89fe-30444672
app_1    | [2021-01-14T04:55:46.511] [INFO] default - Publish task ended
app_1    | Error: cannot get access_token
app_1    |     at WechatSpider.getAccessToken (/app/spiders/wechat.js:88:15)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1    | [2021-01-14T04:55:47.004] [INFO] default - Publish task started
app_1    | [Function: AliyunSpider]
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2021-01-14T04:55:47.404] [INFO] default - navigating to https://developer.aliyun.com/article/new
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 200 26.258 ms - 10625
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 21.136 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 28.584 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 31.573 ms - -
app_1    | GET /articles/5fffcd653b5ccd001c3768a5/tasks 304 25.513 ms - -
app_1    | [2021-01-14T04:56:11.492] [INFO] default - input editor title
app_1    | Error: Evaluation failed: TypeError: Cannot read property 'focus' of null
app_1    |     at inputTitle (__puppeteer_evaluation_script__:3:8)
app_1    |     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1    |   -- ASYNC --
app_1    |     at ExecutionContext.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at DOMWorld.evaluate (/app/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.evaluate (/app/node_modules/puppeteer-core/lib/Page.js:833:43)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at AliyunSpider.inputEditor (/app/spiders/base.js:278:21)
app_1    |     at AliyunSpider.run (/app/spiders/base.js:345:16)
app_1    |     at <anonymous>
app_1    | [2021-01-14T04:56:12.060] [INFO] default - Publish task ended
```
![image](https://user-images.githubusercontent.com/12791216/104546800-f495a480-5667-11eb-94c7-4d4ef167111d.png)
![image](https://user-images.githubusercontent.com/12791216/104546846-09723800-5668-11eb-941c-ffc3fe031003.png)

**Comment by aafnnp** [comment]
大致查看了下，应当是爬虫的时候，获取元素失败导致的

**Comment by acooler15** [comment]
发布现在还是基于头条的v3编辑器做的，现在还没有适配头条的v4编辑器😢

**Comment by aafnnp** [comment]
> 发布现在还是基于头条的v3编辑器做的，现在还没有适配头条的v4编辑器😢

仅 掘金 发布成功哦，其他平台都是失败的

**Comment by tanliyuan** [comment]
> 发布现在还是基于头条的v3编辑器做的，现在还没有适配头条的v4编辑器😢

最新版本已经支持v4
