### ISSUE TITLE
新版拉完代码后mongodb报错

### ISSUE THREAD

**Issue by silsuer** [crawlab-team/artipub#161]
```
(base) ➜  backend git:(master) yarn run dev
yarn run v1.22.4
$ ts-node ./src/server.ts
[2021-04-19T10:44:31.583] [INFO] default - listening on port 3000
(node:43755) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2021-04-19T10:44:31.718] [ERROR] default - MongoError: Index build failed: afe71740-16f0-4ca0-95ce-6ef1c425b21b: Collection artipub.environments ( bda993d8-fec6-41be-82f7-7f82115615bf ) :: caused by :: E11000 duplicate key error collection: artipub.environments index: user_1_name_1 dup key: { user: null, name: null }
    at MessageStream.messageHandler (/Users/hongbaoliu/project/university/artipub/backend/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:467:12)
    at processIncomingData (/Users/hongbaoliu/project/university/artipub/backend/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/Users/hongbaoliu/project/university/artipub/backend/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  ok: 0,
  code: 11000,
  codeName: 'DuplicateKey',
  keyPattern: { user: 1, name: 1 },
  keyValue: { user: null, name: null }
}
```

请问在哪改这个env文件？现在这种情况，在后台可以注册成功，然后登陆也会显示登录成功，但是页面不会跳转

**Comment by tanliyuan** [comment]
增加了登录注册功能后，表的结构发生较大改变，前后不兼容，建议将原来 库名重命名作为备份，之后将文章重新创建。
上面报错是 environments  这个表唯一索引有问题，user , 环境name 是组合唯一索引，删除冲突的就行。

**Comment by silsuer** [comment]
@tanliyuan 谢谢，删除后不再报错了，可是注册成功后，进行登录，登录接口返回值是ok，但是不会跳转到首页，不知为何？

**Comment by tanliyuan** [comment]
清空下cookie再登录试试，之前有人也遇到过，下次我看看原因优化下

**Comment by silsuer** [comment]
我试着清空了cookie，然后重新加载，发现login接口的response header 里存在set-cookie  但是本地的cookie里依旧是空的，所以还是没有跳转

**Comment by tanliyuan** [comment]
set-cookie 里面的域 和你页面的域一样嘛

**Comment by silsuer** [comment]
是一样的，等您更新了上面的问题的时候我再试试吧
