### ISSUE TITLE
发布简书和CSDN报错，这是报错信息

### ISSUE THREAD

**Issue by elevenChen2019** [crawlab-team/artipub#162]
app_1    | [2021-04-21T08:15:49.002] [INFO] default - Publish task started
app_1    | [2021-04-21T08:15:49.004] [INFO] default - [class CsdnSpider extends BaseSpider]
app_1    | [PCR] Chromium revision: 818858
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-818858/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/88.0.4298.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 5.5.0
app_1    | [PCR] Stats saved: node_modules/puppeteer-chromium-resolver/.stats.json
app_1    | [2021-04-21T08:15:49.397] [INFO] default - navigating to https://editor.csdn.net/md/
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 200 23.062 ms - 11476
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 12.631 ms - -
app_1    | [2021-04-21T08:15:58.524] [INFO] default - input editor title
app_1    | [2021-04-21T08:15:58.541] [INFO] default - input editor  content
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 14.999 ms - -
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 41.763 ms - -
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 13.121 ms - -
app_1    | [2021-04-21T08:16:09.674] [ERROR] default - Error: Evaluation failed: TypeError: Cannot set property 'value' of null
app_1    |     at __puppeteer_evaluation_script__:3:27
app_1    |     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
app_1    |     at runMicrotasks (<anonymous>)
app_1    |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
app_1    |     at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
app_1    |     at async CsdnSpider.afterInputEditor (/app/dist/spiders/csdn.js:43:9)
app_1    |     at async CsdnSpider.inputEditor (/app/dist/spiders/base.js:254:9)
app_1    |     at async CsdnSpider.run (/app/dist/spiders/base.js:303:9)
app_1    |     at async ArticlePublisher.run (/app/dist/lib/ArticlePublisher.js:22:17)
app_1    |     at async ArticlePublisher.start (/app/dist/lib/BaseExecutor.js:24:9)
app_1    |     at async /app/dist/exec.js:38:21
app_1    | [2021-04-21T08:16:09.756] [INFO] default - Publish task ended
app_1    | [2021-04-21T08:16:10.004] [INFO] default - Publish task started
app_1    | [2021-04-21T08:16:10.007] [INFO] default - [class JianshuSpider extends BaseSpider]
app_1    | [PCR] Chromium revision: 818858
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-818858/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/88.0.4298.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 5.5.0
app_1    | [PCR] Stats saved: node_modules/puppeteer-chromium-resolver/.stats.json
app_1    | [2021-04-21T08:16:10.379] [INFO] default - navigating to https://www.jianshu.com/writer
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 200 13.634 ms - 11470
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 14.946 ms - -
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 13.394 ms - -
app_1    | [2021-04-21T08:16:27.301] [INFO] default - publishing article
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 25.223 ms - -
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 21.633 ms - -
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 12.558 ms - -
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 20.375 ms - -
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 13.065 ms - -
app_1    | GET /articles/607fce13e7d9c70019f99a7b/tasks 304 13.236 ms - -
app_1    | [2021-04-21T08:16:58.804] [ERROR] default - TimeoutError: Timeout exceeded while waiting for event
app_1    |     at Timeout.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/helper.js:120:28)
app_1    |     at listOnTimeout (node:internal/timers:557:17)
app_1    |     at processTimers (node:internal/timers:500:7)
app_1    | [2021-04-21T08:16:58.876] [INFO] default - Publish task ended

**Comment by xuyisheng** [comment]
发布CSDN，提示 文章Url未保存成功
