### ISSUE TITLE
这是不是依赖图形界面

### ISSUE THREAD

**Issue by yxxhero** [crawlab-team/artipub#22]
这是不是依赖图形界面

**Comment by tikazyq** [comment]
拉取最新的docker或者在系统设置中把chrome浏览器模式设置为关闭

**Comment by tikazyq** [comment]
这是docker下的bug，没有安装x11

**Comment by yxxhero** [comment]
您好 我是在服务器centos上弄的   我需要安装x11么 在docker里  还有您的那个chrome插件安装后会导致整个chrome报错

**Comment by tikazyq** [comment]
docker不用装x11

chrome尽量用最新版本76

**Comment by yxxhero** [comment]
我的78版本
以下是在docker里的报错
(node:23) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
(chrome:62): Gtk-WARNING **: 07:01:03.576: cannot open display: 
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/app/node_modules/puppeteer-core/lib/Launcher.js:348:14)
    at ChildProcess.helper.addEventListener (/app/node_modules/puppeteer-core/lib/Launcher.js:338:60)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at emitWarning (internal/process/promises.js:65:17)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at process._tickCallback (internal/process/next_tick.js:190:7)
(node:23) Error: Failed to launch chrome!
(chrome:62): Gtk-WARNING **: 07:01:03.576: cannot open display: 
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/app/node_modules/puppeteer-core/lib/Launcher.js:348:14)
    at ChildProcess.helper.addEventListener (/app/node_modules/puppeteer-core/lib/Launcher.js:338:60)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)


@tikazyq

**Comment by tikazyq** [comment]
在“系统设置”页面里，将“Chrome浏览器调试”设置为“关闭”

**Comment by yxxhero** [comment]
可以了 但是现在点击 更新cooike状态 提示超时  504   麻烦您了  这是怎么回事

**Comment by tikazyq** [comment]
加微信私聊 tikazyq1

**Comment by tikazyq** [comment]
fixed in ac8b088cb186b4d0ffe3daf143802c1834debe52
