### ISSUE TITLE
文章发布到 SegmentFault 失败

### ISSUE THREAD

**Issue by nettee** [crawlab-team/artipub#25]
如图，一篇文章发布到掘金成功，但发布到 SegmentFault 失败。

![image](https://user-images.githubusercontent.com/3953668/65399851-82a1a800-ddf1-11e9-9f01-8a909e19fb0b.png)

错误信息（docker 的 log）：

```
app_1    | [2019-09-23T02:59:15.003] [INFO] default - Publish task started
app_1    | [PCR] Chromium revision: 686378
app_1    | [PCR] Detected local chromium is already downloaded
app_1    | [PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
app_1    | [PCR] Chromium version: HeadlessChrome/78.0.3882.0
app_1    | [PCR] Chromium launchable: true
app_1    | [PCR] Puppeteer version: 1.20.0
app_1    | [2019-09-23T02:59:15.395] [INFO] default - navigating to https://segmentfault.com/write
app_1    | GET /articles/5d8830a53c42ed001a4bdb01/tasks 200 20.951 ms - 7942
app_1    | [2019-09-23T02:59:23.136] [INFO] default - input editor title and content
app_1    | Error: Evaluation failed: TypeError: Cannot read property 'focus' of null
app_1    |     at inputTitle (__puppeteer_evaluation_script__:3:8)
app_1    |     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1    |   -- ASYNC --
app_1    |     at ExecutionContext.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at DOMWorld.evaluate (/app/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.evaluate (/app/node_modules/puppeteer-core/lib/Page.js:833:43)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at SegmentfaultSpider.inputEditor (/app/spiders/base.js:236:21)
app_1    |     at SegmentfaultSpider.run (/app/spiders/base.js:290:16)
app_1    |     at <anonymous>
app_1    | [2019-09-23T02:59:23.171] [INFO] default - Publish task ended
```

**Comment by nettee** [comment]
经过调试，发现打开 SegmentFault 文章编辑页面 (https://segmentfault.com/write) 时，会自动跳转到一个“关于专栏文章”页面 (https://segmentfault.com/howtowrite) ，需要点一次按钮才能真正进入文章编辑。怀疑是 artipub 没有考虑到这个页面跳转的问题。

P.S. 不知道是不是 SegmentFault 始终会跳转到这个页面。

**Comment by tikazyq** [comment]
我这边没有触发，不知道什么原因，可能是网站改版也说不定，我测试一下，如果可以的话，参考源代码，加一个方法就可以绕过，详细可以微信上交流

**Comment by nettee** [comment]
@tikazyq 我这边测试把写文章的 URL 改成 https://segmentfault.com/write?freshman=1 就可以正常发布，不知道是否适用于所有人。

```diff
diff --git a/spiders/config.js b/spiders/config.js
index 5b9c70a..ffc005b 100644
--- a/spiders/config.js
+++ b/spiders/config.js
@@ -19,7 +19,7 @@ module.exports = {
   segmentfault: {
     urls: {
       login: 'https://segmentfault.com/user/login',
-      editor: 'https://segmentfault.com/write'
+      editor: 'https://segmentfault.com/write?freshman=1'
     },
     loginSel: {
       username: 'input[name="username"]',

```

**Comment by tikazyq** [comment]
先观察一下

**Comment by SaintLoong** [comment]
我也一样得docker，一样得报错

**Comment by tikazyq** [comment]
是用的最新的docker么，能否将日志文件上传看看
