### ISSUE TITLE
掘金发布失败，docker日志如下

### ISSUE THREAD

**Issue by SaintLoong** [crawlab-team/artipub#45]
> OPTIONS /tasks/batch 200 0.194 ms - 2
PUT /tasks/batch 200 22.429 ms - 15
GET /articles/5d905104dd6531001e7cc4c8/tasks 200 13.045 ms - 9582
OPTIONS /tasks/batch 200 0.184 ms - 2
PUT /tasks/batch 200 19.476 ms - 15
POST /articles/5d905104dd6531001e7cc4c8/publish 200 3.168 ms - 15
[2019-09-29T09:29:34.003] [INFO] default - Publish task started
[Function: JuejinSpider]
[PCR] Chromium revision: 686378
[PCR] Detected local chromium is already downloaded
[PCR] Chromium executablePath: /root/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
[PCR] Chromium version: HeadlessChrome/78.0.3882.0
[PCR] Chromium launchable: true
[PCR] Puppeteer version: 1.20.0
[2019-09-29T09:29:34.307] [INFO] default - logging in... navigating to https://juejin.im/login
GET /articles/5d905104dd6531001e7cc4c8/tasks 200 25.930 ms - 9587
[2019-09-29T09:29:40.114] [INFO] default - Logged in
[2019-09-29T09:29:40.114] [INFO] default - navigating to https://juejin.im/editor/drafts/new
GET /articles/5d905104dd6531001e7cc4c8/tasks 304 11.074 ms - -
GET /articles/5d905104dd6531001e7cc4c8/tasks 304 18.417 ms - -
GET /articles/5d905104dd6531001e7cc4c8/tasks 304 10.472 ms - -
GET /articles/5d905104dd6531001e7cc4c8/tasks 304 11.335 ms - -
GET /articles/5d905104dd6531001e7cc4c8/tasks 304 11.934 ms - -
GET /articles/5d905104dd6531001e7cc4c8/tasks 304 14.273 ms - -
GET /articles/5d905104dd6531001e7cc4c8/tasks 304 10.716 ms - -
{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/app/node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.goto (/app/node_modules/puppeteer-core/lib/Page.js:674:49)
    at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
    at JuejinSpider.afterGoToEditor (/app/spiders/juejin.js:6:25)
    at JuejinSpider.goToEditor (/app/spiders/base.js:202:16)
    at <anonymous> name: 'TimeoutError' }
[2019-09-29T09:30:15.844] [INFO] default - Publish task ended
GET /articles/5d905104dd6531001e7cc4c8/tasks 200 10.691 ms - 9523

**Comment by tikazyq** [comment]
网络超时了，可以重新发布几次试试看

**Comment by azl397985856** [comment]
就我而言，很有可能是你没有登陆。 你可以先确认以下。  就这一点来说，我认为你们应该优化错误提示。 比如改成“未登录，请先登陆”
